// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pong.proto

/*
Package pong is a generated protocol buffer package.

It is generated from these files:
	pong.proto

It has these top-level messages:
	SetPlayerPositionRequest
	SetPlayerPositionReply
*/
package pong

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SetPlayerPositionRequest struct {
	Id int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	X  int32 `protobuf:"varint,2,opt,name=X" json:"X,omitempty"`
	Y  int32 `protobuf:"varint,3,opt,name=Y" json:"Y,omitempty"`
}

func (m *SetPlayerPositionRequest) Reset()                    { *m = SetPlayerPositionRequest{} }
func (m *SetPlayerPositionRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerPositionRequest) ProtoMessage()               {}
func (*SetPlayerPositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SetPlayerPositionRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetPlayerPositionRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetPlayerPositionRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

// The response message containing the greetings
type SetPlayerPositionReply struct {
	Id int32 `protobuf:"varint,1,opt,name=Id" json:"Id,omitempty"`
	X  int32 `protobuf:"varint,2,opt,name=X" json:"X,omitempty"`
	Y  int32 `protobuf:"varint,3,opt,name=Y" json:"Y,omitempty"`
}

func (m *SetPlayerPositionReply) Reset()                    { *m = SetPlayerPositionReply{} }
func (m *SetPlayerPositionReply) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerPositionReply) ProtoMessage()               {}
func (*SetPlayerPositionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SetPlayerPositionReply) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *SetPlayerPositionReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetPlayerPositionReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*SetPlayerPositionRequest)(nil), "pong.SetPlayerPositionRequest")
	proto.RegisterType((*SetPlayerPositionReply)(nil), "pong.SetPlayerPositionReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ponger service

type PongerClient interface {
	// Sends a greeting
	SetPlayerPosition(ctx context.Context, in *SetPlayerPositionRequest, opts ...grpc.CallOption) (*SetPlayerPositionReply, error)
}

type pongerClient struct {
	cc *grpc.ClientConn
}

func NewPongerClient(cc *grpc.ClientConn) PongerClient {
	return &pongerClient{cc}
}

func (c *pongerClient) SetPlayerPosition(ctx context.Context, in *SetPlayerPositionRequest, opts ...grpc.CallOption) (*SetPlayerPositionReply, error) {
	out := new(SetPlayerPositionReply)
	err := grpc.Invoke(ctx, "/pong.Ponger/SetPlayerPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ponger service

type PongerServer interface {
	// Sends a greeting
	SetPlayerPosition(context.Context, *SetPlayerPositionRequest) (*SetPlayerPositionReply, error)
}

func RegisterPongerServer(s *grpc.Server, srv PongerServer) {
	s.RegisterService(&_Ponger_serviceDesc, srv)
}

func _Ponger_SetPlayerPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongerServer).SetPlayerPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pong.Ponger/SetPlayerPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongerServer).SetPlayerPosition(ctx, req.(*SetPlayerPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ponger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pong.Ponger",
	HandlerType: (*PongerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPlayerPosition",
			Handler:    _Ponger_SetPlayerPosition_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pong.proto",
}

func init() { proto.RegisterFile("pong.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0xc8, 0xcf, 0x4b,
	0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xdc, 0xb8, 0x24, 0x82, 0x53,
	0x4b, 0x02, 0x72, 0x12, 0x2b, 0x53, 0x8b, 0x02, 0xf2, 0x8b, 0x33, 0x4b, 0x32, 0xf3, 0xf3, 0x82,
	0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xf8, 0xb8, 0x98, 0x3c, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x58, 0x83, 0x80, 0x2c, 0x21, 0x1e, 0x2e, 0xc6, 0x08, 0x09, 0x26, 0x30, 0x97, 0x31, 0x02,
	0xc4, 0x8b, 0x94, 0x60, 0x86, 0xf0, 0x22, 0x95, 0x5c, 0xb8, 0xc4, 0xb0, 0x98, 0x53, 0x90, 0x53,
	0x49, 0x8a, 0x29, 0x46, 0xb1, 0x5c, 0x6c, 0x01, 0x40, 0x57, 0xa5, 0x16, 0x09, 0x05, 0x73, 0x09,
	0x62, 0x98, 0x27, 0x24, 0xa7, 0x07, 0x76, 0x3f, 0x2e, 0x07, 0x4b, 0xc9, 0xe0, 0x94, 0x07, 0x3a,
	0x44, 0x89, 0xc1, 0xc9, 0x80, 0x4b, 0x3a, 0x33, 0x5f, 0x2f, 0xbd, 0xa8, 0x20, 0x59, 0x2f, 0xb5,
	0x22, 0x31, 0xb7, 0x20, 0x27, 0xb5, 0x58, 0x2f, 0x23, 0x35, 0x27, 0x27, 0xbf, 0x3c, 0xbf, 0x28,
	0x27, 0xc5, 0x89, 0xdf, 0x03, 0xc4, 0x0e, 0x07, 0xb1, 0x03, 0x40, 0x41, 0x14, 0xc0, 0x98, 0xc4,
	0x06, 0x0e, 0x2b, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7f, 0xc5, 0xbe, 0xe3, 0x39, 0x01,
	0x00, 0x00,
}
