// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pong.proto

/*
Package pong is a generated protocol buffer package.

It is generated from these files:
	pong.proto

It has these top-level messages:
	GetScoreRequest
	GetScoreReply
	SetPlayerPositionRequest
	SetPlayerPositionReply
	GetBallPositionRequest
	GetBallPositionReply
	IdentifyPlayerRequest
	IdentifyPlayerReply
	GetOpponentRequest
	GetOpponentReply
*/
package pong

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetScoreRequest struct {
	Handshake string `protobuf:"bytes,1,opt,name=Handshake" json:"Handshake,omitempty"`
}

func (m *GetScoreRequest) Reset()                    { *m = GetScoreRequest{} }
func (m *GetScoreRequest) String() string            { return proto.CompactTextString(m) }
func (*GetScoreRequest) ProtoMessage()               {}
func (*GetScoreRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetScoreRequest) GetHandshake() string {
	if m != nil {
		return m.Handshake
	}
	return ""
}

type GetScoreReply struct {
	Score0 int32 `protobuf:"varint,1,opt,name=Score0" json:"Score0,omitempty"`
	Score1 int32 `protobuf:"varint,2,opt,name=Score1" json:"Score1,omitempty"`
}

func (m *GetScoreReply) Reset()                    { *m = GetScoreReply{} }
func (m *GetScoreReply) String() string            { return proto.CompactTextString(m) }
func (*GetScoreReply) ProtoMessage()               {}
func (*GetScoreReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetScoreReply) GetScore0() int32 {
	if m != nil {
		return m.Score0
	}
	return 0
}

func (m *GetScoreReply) GetScore1() int32 {
	if m != nil {
		return m.Score1
	}
	return 0
}

type SetPlayerPositionRequest struct {
	Handshake    string `protobuf:"bytes,1,opt,name=Handshake" json:"Handshake,omitempty"`
	PlayerNumber int32  `protobuf:"varint,2,opt,name=PlayerNumber" json:"PlayerNumber,omitempty"`
	X            int32  `protobuf:"varint,3,opt,name=X" json:"X,omitempty"`
	Y            int32  `protobuf:"varint,4,opt,name=Y" json:"Y,omitempty"`
}

func (m *SetPlayerPositionRequest) Reset()                    { *m = SetPlayerPositionRequest{} }
func (m *SetPlayerPositionRequest) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerPositionRequest) ProtoMessage()               {}
func (*SetPlayerPositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SetPlayerPositionRequest) GetHandshake() string {
	if m != nil {
		return m.Handshake
	}
	return ""
}

func (m *SetPlayerPositionRequest) GetPlayerNumber() int32 {
	if m != nil {
		return m.PlayerNumber
	}
	return 0
}

func (m *SetPlayerPositionRequest) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetPlayerPositionRequest) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type SetPlayerPositionReply struct {
	PlayerNumber int32 `protobuf:"varint,1,opt,name=PlayerNumber" json:"PlayerNumber,omitempty"`
	X            int32 `protobuf:"varint,2,opt,name=X" json:"X,omitempty"`
	Y            int32 `protobuf:"varint,3,opt,name=Y" json:"Y,omitempty"`
}

func (m *SetPlayerPositionReply) Reset()                    { *m = SetPlayerPositionReply{} }
func (m *SetPlayerPositionReply) String() string            { return proto.CompactTextString(m) }
func (*SetPlayerPositionReply) ProtoMessage()               {}
func (*SetPlayerPositionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SetPlayerPositionReply) GetPlayerNumber() int32 {
	if m != nil {
		return m.PlayerNumber
	}
	return 0
}

func (m *SetPlayerPositionReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *SetPlayerPositionReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type GetBallPositionRequest struct {
	Handshake string `protobuf:"bytes,1,opt,name=Handshake" json:"Handshake,omitempty"`
}

func (m *GetBallPositionRequest) Reset()                    { *m = GetBallPositionRequest{} }
func (m *GetBallPositionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetBallPositionRequest) ProtoMessage()               {}
func (*GetBallPositionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetBallPositionRequest) GetHandshake() string {
	if m != nil {
		return m.Handshake
	}
	return ""
}

type GetBallPositionReply struct {
	X int32 `protobuf:"varint,1,opt,name=X" json:"X,omitempty"`
	Y int32 `protobuf:"varint,2,opt,name=Y" json:"Y,omitempty"`
}

func (m *GetBallPositionReply) Reset()                    { *m = GetBallPositionReply{} }
func (m *GetBallPositionReply) String() string            { return proto.CompactTextString(m) }
func (*GetBallPositionReply) ProtoMessage()               {}
func (*GetBallPositionReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetBallPositionReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GetBallPositionReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

type IdentifyPlayerRequest struct {
	Room string `protobuf:"bytes,1,opt,name=Room" json:"Room,omitempty"`
}

func (m *IdentifyPlayerRequest) Reset()                    { *m = IdentifyPlayerRequest{} }
func (m *IdentifyPlayerRequest) String() string            { return proto.CompactTextString(m) }
func (*IdentifyPlayerRequest) ProtoMessage()               {}
func (*IdentifyPlayerRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *IdentifyPlayerRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

type IdentifyPlayerReply struct {
	PlayerNumber int32  `protobuf:"varint,1,opt,name=PlayerNumber" json:"PlayerNumber,omitempty"`
	Handshake    string `protobuf:"bytes,2,opt,name=Handshake" json:"Handshake,omitempty"`
}

func (m *IdentifyPlayerReply) Reset()                    { *m = IdentifyPlayerReply{} }
func (m *IdentifyPlayerReply) String() string            { return proto.CompactTextString(m) }
func (*IdentifyPlayerReply) ProtoMessage()               {}
func (*IdentifyPlayerReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *IdentifyPlayerReply) GetPlayerNumber() int32 {
	if m != nil {
		return m.PlayerNumber
	}
	return 0
}

func (m *IdentifyPlayerReply) GetHandshake() string {
	if m != nil {
		return m.Handshake
	}
	return ""
}

type GetOpponentRequest struct {
	PlayerNumber int32  `protobuf:"varint,1,opt,name=PlayerNumber" json:"PlayerNumber,omitempty"`
	Handshake    string `protobuf:"bytes,2,opt,name=Handshake" json:"Handshake,omitempty"`
}

func (m *GetOpponentRequest) Reset()                    { *m = GetOpponentRequest{} }
func (m *GetOpponentRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOpponentRequest) ProtoMessage()               {}
func (*GetOpponentRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetOpponentRequest) GetPlayerNumber() int32 {
	if m != nil {
		return m.PlayerNumber
	}
	return 0
}

func (m *GetOpponentRequest) GetHandshake() string {
	if m != nil {
		return m.Handshake
	}
	return ""
}

type GetOpponentReply struct {
	PlayerNumber int32 `protobuf:"varint,1,opt,name=PlayerNumber" json:"PlayerNumber,omitempty"`
	X            int32 `protobuf:"varint,2,opt,name=X" json:"X,omitempty"`
	Y            int32 `protobuf:"varint,3,opt,name=Y" json:"Y,omitempty"`
}

func (m *GetOpponentReply) Reset()                    { *m = GetOpponentReply{} }
func (m *GetOpponentReply) String() string            { return proto.CompactTextString(m) }
func (*GetOpponentReply) ProtoMessage()               {}
func (*GetOpponentReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *GetOpponentReply) GetPlayerNumber() int32 {
	if m != nil {
		return m.PlayerNumber
	}
	return 0
}

func (m *GetOpponentReply) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *GetOpponentReply) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func init() {
	proto.RegisterType((*GetScoreRequest)(nil), "pong.GetScoreRequest")
	proto.RegisterType((*GetScoreReply)(nil), "pong.GetScoreReply")
	proto.RegisterType((*SetPlayerPositionRequest)(nil), "pong.SetPlayerPositionRequest")
	proto.RegisterType((*SetPlayerPositionReply)(nil), "pong.SetPlayerPositionReply")
	proto.RegisterType((*GetBallPositionRequest)(nil), "pong.GetBallPositionRequest")
	proto.RegisterType((*GetBallPositionReply)(nil), "pong.GetBallPositionReply")
	proto.RegisterType((*IdentifyPlayerRequest)(nil), "pong.IdentifyPlayerRequest")
	proto.RegisterType((*IdentifyPlayerReply)(nil), "pong.IdentifyPlayerReply")
	proto.RegisterType((*GetOpponentRequest)(nil), "pong.GetOpponentRequest")
	proto.RegisterType((*GetOpponentReply)(nil), "pong.GetOpponentReply")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Ponger service

type PongerClient interface {
	// Sends a player position
	SetPlayerPosition(ctx context.Context, in *SetPlayerPositionRequest, opts ...grpc.CallOption) (*SetPlayerPositionReply, error)
	// Gets the ball position
	GetBallPosition(ctx context.Context, in *GetBallPositionRequest, opts ...grpc.CallOption) (*GetBallPositionReply, error)
	// Get opponent position
	GetOpponent(ctx context.Context, in *GetOpponentRequest, opts ...grpc.CallOption) (*GetOpponentReply, error)
	// Get Player number and the handshake which will be required in the other calls
	IdentifyPlayer(ctx context.Context, in *IdentifyPlayerRequest, opts ...grpc.CallOption) (*IdentifyPlayerReply, error)
	GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreReply, error)
}

type pongerClient struct {
	cc *grpc.ClientConn
}

func NewPongerClient(cc *grpc.ClientConn) PongerClient {
	return &pongerClient{cc}
}

func (c *pongerClient) SetPlayerPosition(ctx context.Context, in *SetPlayerPositionRequest, opts ...grpc.CallOption) (*SetPlayerPositionReply, error) {
	out := new(SetPlayerPositionReply)
	err := grpc.Invoke(ctx, "/pong.Ponger/SetPlayerPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongerClient) GetBallPosition(ctx context.Context, in *GetBallPositionRequest, opts ...grpc.CallOption) (*GetBallPositionReply, error) {
	out := new(GetBallPositionReply)
	err := grpc.Invoke(ctx, "/pong.Ponger/GetBallPosition", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongerClient) GetOpponent(ctx context.Context, in *GetOpponentRequest, opts ...grpc.CallOption) (*GetOpponentReply, error) {
	out := new(GetOpponentReply)
	err := grpc.Invoke(ctx, "/pong.Ponger/GetOpponent", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongerClient) IdentifyPlayer(ctx context.Context, in *IdentifyPlayerRequest, opts ...grpc.CallOption) (*IdentifyPlayerReply, error) {
	out := new(IdentifyPlayerReply)
	err := grpc.Invoke(ctx, "/pong.Ponger/IdentifyPlayer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pongerClient) GetScore(ctx context.Context, in *GetScoreRequest, opts ...grpc.CallOption) (*GetScoreReply, error) {
	out := new(GetScoreReply)
	err := grpc.Invoke(ctx, "/pong.Ponger/GetScore", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Ponger service

type PongerServer interface {
	// Sends a player position
	SetPlayerPosition(context.Context, *SetPlayerPositionRequest) (*SetPlayerPositionReply, error)
	// Gets the ball position
	GetBallPosition(context.Context, *GetBallPositionRequest) (*GetBallPositionReply, error)
	// Get opponent position
	GetOpponent(context.Context, *GetOpponentRequest) (*GetOpponentReply, error)
	// Get Player number and the handshake which will be required in the other calls
	IdentifyPlayer(context.Context, *IdentifyPlayerRequest) (*IdentifyPlayerReply, error)
	GetScore(context.Context, *GetScoreRequest) (*GetScoreReply, error)
}

func RegisterPongerServer(s *grpc.Server, srv PongerServer) {
	s.RegisterService(&_Ponger_serviceDesc, srv)
}

func _Ponger_SetPlayerPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPlayerPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongerServer).SetPlayerPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pong.Ponger/SetPlayerPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongerServer).SetPlayerPosition(ctx, req.(*SetPlayerPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ponger_GetBallPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBallPositionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongerServer).GetBallPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pong.Ponger/GetBallPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongerServer).GetBallPosition(ctx, req.(*GetBallPositionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ponger_GetOpponent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOpponentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongerServer).GetOpponent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pong.Ponger/GetOpponent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongerServer).GetOpponent(ctx, req.(*GetOpponentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ponger_IdentifyPlayer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdentifyPlayerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongerServer).IdentifyPlayer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pong.Ponger/IdentifyPlayer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongerServer).IdentifyPlayer(ctx, req.(*IdentifyPlayerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ponger_GetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PongerServer).GetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pong.Ponger/GetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PongerServer).GetScore(ctx, req.(*GetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Ponger_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pong.Ponger",
	HandlerType: (*PongerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetPlayerPosition",
			Handler:    _Ponger_SetPlayerPosition_Handler,
		},
		{
			MethodName: "GetBallPosition",
			Handler:    _Ponger_GetBallPosition_Handler,
		},
		{
			MethodName: "GetOpponent",
			Handler:    _Ponger_GetOpponent_Handler,
		},
		{
			MethodName: "IdentifyPlayer",
			Handler:    _Ponger_IdentifyPlayer_Handler,
		},
		{
			MethodName: "GetScore",
			Handler:    _Ponger_GetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pong.proto",
}

func init() { proto.RegisterFile("pong.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x54, 0xcf, 0x6f, 0xda, 0x30,
	0x14, 0x5e, 0x02, 0x43, 0xe3, 0x8d, 0x8d, 0xcd, 0x8c, 0x28, 0x0b, 0x68, 0x9a, 0x7c, 0x9a, 0x34,
	0x29, 0x03, 0x26, 0x55, 0xbd, 0x55, 0xe5, 0x52, 0x5a, 0xa9, 0x6d, 0x14, 0xa4, 0x02, 0xc7, 0x00,
	0x2e, 0x44, 0x35, 0x71, 0x9a, 0x04, 0x15, 0xfe, 0xf0, 0xde, 0x9b, 0x38, 0x09, 0x24, 0x21, 0x91,
	0xa8, 0xda, 0xdb, 0xfb, 0xf9, 0x7d, 0x9f, 0xed, 0xe7, 0x07, 0x60, 0x33, 0x6b, 0xa1, 0xda, 0x0e,
	0xf3, 0x18, 0x2a, 0x07, 0x36, 0xfe, 0x07, 0xf5, 0x0b, 0xe2, 0x0d, 0x67, 0xcc, 0x21, 0x3a, 0x79,
	0x5c, 0x13, 0xd7, 0x43, 0x6d, 0xa8, 0x0e, 0x0c, 0x6b, 0xee, 0x2e, 0x8d, 0x07, 0x22, 0x0b, 0xbf,
	0x85, 0x3f, 0x55, 0x7d, 0x1f, 0xc0, 0x67, 0xf0, 0x65, 0xdf, 0x60, 0xd3, 0x2d, 0x92, 0xa0, 0xc2,
	0xbd, 0x0e, 0xaf, 0xfd, 0xa8, 0x47, 0xde, 0x2e, 0xde, 0x95, 0xc5, 0x44, 0xbc, 0x8b, 0x37, 0x20,
	0x0f, 0x89, 0xa7, 0x51, 0x63, 0x4b, 0x1c, 0x8d, 0xb9, 0xa6, 0x67, 0x32, 0xeb, 0x28, 0x6a, 0x84,
	0xa1, 0x16, 0xb6, 0xdd, 0xac, 0x57, 0x53, 0xe2, 0x44, 0xb8, 0xa9, 0x18, 0xaa, 0x81, 0x30, 0x96,
	0x4b, 0x3c, 0x21, 0x8c, 0x03, 0x6f, 0x22, 0x97, 0x43, 0x6f, 0x82, 0xc7, 0x20, 0xe5, 0x30, 0x07,
	0x67, 0xc8, 0x22, 0x0b, 0x45, 0xc8, 0x62, 0x0a, 0xb9, 0x14, 0x23, 0x9f, 0x80, 0xe4, 0x5f, 0x4a,
	0xdf, 0xa0, 0xf4, 0x55, 0x27, 0xc2, 0x3d, 0xf8, 0x71, 0xd0, 0x17, 0xe8, 0xe1, 0x5c, 0x42, 0x8a,
	0x4b, 0x8c, 0xb9, 0xfe, 0x42, 0xf3, 0x72, 0x4e, 0x2c, 0xcf, 0xbc, 0xdf, 0x86, 0xfa, 0x62, 0x2a,
	0x04, 0x65, 0x9d, 0xb1, 0x55, 0xc4, 0xc2, 0x6d, 0x3c, 0x82, 0x46, 0xb6, 0xf8, 0xd8, 0xf3, 0xa6,
	0x94, 0x8b, 0x59, 0xe5, 0x77, 0x80, 0x7c, 0xe5, 0xb7, 0xb6, 0x3f, 0x44, 0x3e, 0x7c, 0x2c, 0xe1,
	0xed, 0xb8, 0x3a, 0x7c, 0x4b, 0xe1, 0xbe, 0xc3, 0xeb, 0xf4, 0x9e, 0x45, 0xa8, 0x68, 0xfe, 0xb0,
	0xfb, 0x65, 0x43, 0xf8, 0x7e, 0x30, 0x02, 0xe8, 0x97, 0xca, 0xbf, 0x45, 0xd1, 0x54, 0x2a, 0xed,
	0xc2, 0xbc, 0xaf, 0x0e, 0x7f, 0x40, 0xd7, 0xfc, 0x0f, 0x25, 0x5f, 0x11, 0x45, 0x2d, 0xf9, 0x43,
	0xa1, 0x28, 0x05, 0xd9, 0x10, 0xee, 0x1c, 0x3e, 0x27, 0xae, 0x00, 0xc9, 0xbb, 0xe2, 0xcc, 0x6d,
	0x2b, 0x52, 0x4e, 0x26, 0x84, 0xb8, 0x82, 0xaf, 0xe9, 0x67, 0x47, 0xad, 0xb0, 0x36, 0x77, 0x72,
	0x94, 0x9f, 0xf9, 0xc9, 0x10, 0xeb, 0x14, 0x3e, 0xc5, 0x1f, 0x1e, 0x35, 0x77, 0x8c, 0xc9, 0x8d,
	0xa1, 0x34, 0xb2, 0x61, 0xde, 0xd9, 0xef, 0x40, 0xcb, 0x64, 0xea, 0xc2, 0xb1, 0x67, 0x2a, 0xd9,
	0x18, 0x2b, 0x9b, 0x12, 0x57, 0x5d, 0x12, 0x4a, 0xd9, 0x13, 0x73, 0xe8, 0xbc, 0x5f, 0x1f, 0x04,
	0xf6, 0x28, 0xb0, 0xb5, 0x60, 0x23, 0x69, 0xc2, 0xb4, 0xc2, 0x57, 0xd3, 0xff, 0x97, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x03, 0xd9, 0x8d, 0x8e, 0xa8, 0x04, 0x00, 0x00,
}
